#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create mesh
runApplication blockMesh

# -- Set fields
#./iPFrun
bash ./zeroFieldRun

# -- Add internal patch
#runApplication addEmptyPatch internalPatch internal -overwrite

# -- Decompose the case
runApplication decomposePar

# -- Run the calc
runParallel threePhaseDensityFoam2D

# -- Remove old 0 folder
rm -r 0

# -- Reconstruct the case
runApplication reconstructPar -withZero

# -- Remove individual processor folders
rm -r processor*

# ----------------------------------------------------------------- end-of-file
